export const USER_ROUTE_PATH_MAP = {
  OTHER: '*',
  TOP: '/',
  WORKS: '/works',
  NOTIFICATIONS: '/notifications',
} as const;

const ADMIN_ROUTE_TOP = '/admin';

export const ADMIN_ROUTE_PATH_MAP = {
  OTHER: '/*',
  TOP: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  WORKS: '/works',
  NOTIFICATIONS: '/notifications',
  MEMBERS: '/members',
  OGP_SETTING: '/ogpSetting',
  OGP_SETTING_DETAIL: '/ogpSetting/detail',
  MYPAGE: '/mypage',
} as const;

export const ADMIN_ROUTE_FULL_PATH_MAP = {
  TOP: ADMIN_ROUTE_TOP,
  LOGIN: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.LOGIN}`,
  LOGOUT: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.LOGOUT}`,
  WORKS: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.WORKS}`,
  NOTIFICATIONS: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.NOTIFICATIONS}`,
  MEMBERS: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.MEMBERS}`,
  OGP_SETTING: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.OGP_SETTING}`,
  OGP_SETTING_DETAIL: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.OGP_SETTING_DETAIL}`,
  MYPAGE: `${ADMIN_ROUTE_TOP}${ADMIN_ROUTE_PATH_MAP.MYPAGE}`,
} as const;
