version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: ./api
    pattern: "**"
    owner: fuga
    group: fuga
    mode: 777
    type:
      - directory

hooks:
  AfterInstall:
    - location: ./scripts_for_deploy/after_install.sh
      runas: ec2-user
      
  ApplicationStart:
    - location: ./scripts_for_deploy/application_start.sh
      runas: root