version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    
hooks:
  Install:
    - location: scripts_for_deploy/install.sh
      timeout: 120
      runas: root

  AfterInstall:
    - location: scripts_for_deploy/after_install.sh
      timeout: 10
      runas: root
      
  ApplicationStart:
    - location: scripts_for_deploy/application_start.sh
      timeout: 10
      runas: root