version: 0.0

os: linux

files:
  - source: /api
    destination: /var/www/html

hooks:
  Install:
    - location: scripts_for_deploy/install.sh
      timeout: 120
      runas: root

  AfterInstall:
    - location: scripts_for_deploy/after_install.sh
      timeout: 10
      runas: root
      
  ApplicationStart:
    - location: scripts_for_deploy/application_start.sh
      timeout: 10
      runas: root