version: 0.0

os: linux

files:
  - source: ./
    destination: /var/www/html

hooks:
  AfterInstall:
    - location: scripts_for_deploy/after_install.sh
      runas: root
      
  ApplicationStart:
    - location: scripts_for_deploy/application_start.sh
      runas: root