version: 0.0

os: linux

files:
  - source: ./
    destination: /var/www/html

permissions:
  - object: /var/www/html/api
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts_for_deploy/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts_for_deploy/after_install.sh
      runas: root
      
  ApplicationStart:
    - location: scripts_for_deploy/application_start.sh
      runas: root