version: 0.0

os: linux

files:
  - source: ./
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts_for_deploy/after_install.sh
      runas: ec2-user
      
  ApplicationStart:
    - location: scripts_for_deploy/application_start.sh
      runas: ec2-user