name: MirroringForProduction

on:
  push:
    branches:
      - api/production
  delete:
    branches:
      - api/production

jobs:
  to_codecommit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/HomePage2023
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY_FOR_CODE_COMMIT }}
          ssh_username:
            ${{ secrets.SSH_PRIVATE_ID_KEY_FOR_CODE_COMMIT }}