name: CopyToS3

on:
  push:
    branches:
      - front/production
  delete:
    branches:
      - front/production

jobs:
  to_codecommit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master 

      - name: Install Dependencies
        run: |
          yarn install
        working-directory: ./client

      - name: Build
        run:  |
          yarn build
        working-directory: ./client

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 build s3://makeit-homepage
        working-directory: ./client
